### PR TITLE
ref(colibri2 session participant re-invite): re-invite user on unknown endpoint error

### PR DESCRIPTION
**Pull request by mykhailo-ua**
Added functionality to re-invite participant when UNKNOWN_ENDPOINT Colibri2Error happened instead of recreating the whole bridge and re-invite all participants. It can happen when endpoint is expired on jvb but jicofo tries to send update about this endpoint and gets error back.
Added this change as part of https://github.com/jitsi/jicofo/issues/1047

### CODE REVIEW

**Comment by bgrozev** [comment]
Hey @mykhailo-ua,

This looks good to me. I reverted some of the changes in JitsiMeetConferenceImpl, because if we use `updateParticipant = false` we will fail to send `source-remove` to the other participants in the conference. With my change, we will log "No ParticipantInfo for $participantId" from `ColibriV2SessionManager`, but I think that's OK.

Let me know what you think, and if you're able to run any additional tests with the current state of the two remaining PRs that would be useful.

**Comment by bgrozev** [comment]
Jenkins add to whitelist

**Review by JonathanLennox — APPROVED** [review]

**Comment by mykhailo-ua** [comment]
Hey guys, I tested the latest changes for jicofo and jvb (https://github.com/jitsi/jitsi-videobridge/pull/1999), which is working for us as well, but during re-inviting participant we have  logged the jicofo error `No ParticipantInfo for XXX` which we would like to avoid. 
There is no point sending update message/or logging error if we already know that jvb endpoint is not present [error_creation_link](https://github.com/jitsi/jicofo/blob/eab721e557520bf47c2362c6618831ec499bb33d/jicofo-selector/src/main/kotlin/org/jitsi/jicofo/bridge/colibri/ColibriV2SessionManager.kt#L531)
Tis error is generated as part of removing participant source [link](https://github.com/jitsi/jicofo/blob/master/jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java#L1196) from re-inviting participants method [link](https://github.com/jitsi/jicofo/blob/master/jicofo/src/main/java/org/jitsi/jicofo/conference/JitsiMeetConferenceImpl.java#L1670) 
My original commit contains this change to eliminate logging the error (pic below), but probably there would be more elegant way how to do it. 
Screenshot 2023-03-23 at 17 39 36

**Comment by bgrozev** [comment]
See my comment above: the original commit introduces a problem because `sendSourceRemove` is not called for the participant being re-invited. I thought the extra code and complexity just to avoid a log was too much, so I removed it, but feel free to re-introduce it in a way that avoids the other problem.

**Comment by mykhailo-ua** [comment]
> 

Aha, sorry missed that comment regarding `sendSourceRemove`, but I think this is just the question of moving if statement to the right place (pic below). For us avoiding extra error logs means less error notifications which requires time for investigation, so I would add that part if you don't mind. Let me do it tomorrow and test if this is working fine. 
Screenshot 2023-03-23 at 18 25 43

**Review by bgrozev — APPROVED** [review]

**Comment by bgrozev** [comment]
Thanks!

**Pull request merged**
