### PR TITLE
Update slf4j to 1.7.32

### PR DESCRIPTION
**Pull request by Neustradamus**
http://www.slf4j.org/news.html

### CODE REVIEW

**Comment by bgrozev** [comment]
Hey thanks for all the updates. Can you remind me if you've signed the CLA (feel free to email me).

**Comment by Neustradamus** [comment]
@bgrozev, @saghul: One PR here.

**Comment by Neustradamus** [comment]
@bgrozev: Why it has been closed?

**Comment by saghul** [comment]
Because it no longer applies AFAIS since the dep has been updated.

**Comment by Neustradamus** [comment]
@saghul: When?

This PR has been created "April 12, 2020".

**Comment by Neustradamus** [comment]
And now there are:
2022-02-08 - Release of SLF4J 1.7.36 & 2022-11-25 - Release of SLF4J 2.0.5:
- https://www.slf4j.org/news.html

**Comment by bgrozev** [comment]
> @saghul: My PR has been created "April 12, 2020".
> 
> I see now that a PR, a long time after has been done with this change, it is not SERIOUS!

April 12, 2020 is also the day I asked you about your CLA, which you never followed up on. Do you have any actual contributions to make, or are you just going to continue wasting people's time with PRs that may or may not compile and just bump random dependency versions without a clear reason? Do you actually use this project, or are you here just to comment?

**Comment by saghul** [comment]
I will also add that this PR was open mid 2020, and in case you forgot, we were not idling around at that time, it was kinda busy, to put it mildly.

**Pull request closed without merging**
