### PR TITLE
Make Jicofo max memory configurable

### PR DESCRIPTION
**Pull request by CPWeaver**
Just a simple change to optionally configure jicofo max memory (-Xmx) from an environment variable.

### CODE REVIEW

**Comment by CPWeaver** [comment]
We have signed a corporate agreement, can you add me to the list with @dwilson6 and @PetroccoCo?

**Comment by PetroccoCo** [comment]
Not sure if it's needed but I can verify @CPWeaver is covered under our corporate agreement.

**Comment by alexanderankin** [comment]
Bumping this, can this be merged? I was gonna submit this same patch, I am trying to configure this like the equivalent `VIDEOBRIDGE_MAX_MEMORY=3072m` setting that exists here https://github.com/jitsi/jitsi-videobridge/blob/master/resources/jvb.sh#L27

it would make sense for the repositories to be consistent in this way.

**Comment by bgrozev** [comment]
See #540

**Pull request closed without merging**
