### PR TITLE
Don't expose password & secret in process listing

### LINKED ISSUE #258: should read password from file, at least to remove it from process list
User password is visible in process list, is there a different way to start jicofo?

### LINKED ISSUE #504: Don't expose password in process listing
## Description
The service will use the authentication password as a command line option (`--user_password=`).
This will allow **any** user on this system to obtain the password from the process table (`ps ...`)

---

## Current behavior
The service will use the authentication password as a command line option (`--user_password=`).
This will allow **any** user on this system to obtain the password from the process table (`ps ...`)

---

## Possible Solution
I haven't touched Java for years, but if I'm recalling correctly the command line arguments  are not immutable in Java (they aren't in C/Go/Rust).

Unlike "classic" UNIX systems the process arguments on Linux are not read only. Changing the relevant argument to some obfuscated value (after processing them) will be reflected in the process output of the operating system.

This can be used to prevent access to the password/shared secrets to anyone running `ps`.

### PR DESCRIPTION
**Pull request by obfusk**
Fixes #504.
Fixes #258.

### CODE REVIEW

**Comment by bgrozev** [comment]
jenkins please test this

**Comment by bgrozev** [comment]
ok to test

**Comment by damencho** [comment]
Can you fix the tests as they are failing:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/jenkins/jicofo/src/main/java/org/jitsi/jicofo/Main.java:[152,13] cannot find symbol
  symbol:   method isNullOrEmpty(java.lang.String)
  location: class org.jitsi.jicofo.Main
[ERROR] /home/jenkins/jicofo/src/main/java/org/jitsi/jicofo/Main.java:[183,13] cannot find symbol
  symbol:   variable StringUtils
  location: class org.jitsi.jicofo.Main
[ERROR] /home/jenkins/jicofo/src/main/java/org/jitsi/jicofo/Main.java:[196,13] cannot find symbol
  symbol:   variable StringUtils
  location: class org.jitsi.jicofo.Main
[INFO] 3 errors 
```

**Comment by obfusk** [comment]
Should be fixed now.

**Comment by damencho** [comment]
Now the tests are failing because your matching PR in jvb repo is failing to be merged: https://github.com/jitsi/jitsi-videobridge/pull/1241

**Comment by obfusk** [comment]
I see that PR is no longer necessary since the XMPP component was removed.

**Pull request merged**
