### PR TITLE
fix: Fix a NPE when chatRoom is null.

### PR DESCRIPTION
**Pull request by bgrozev**

### CODE REVIEW

**Comment by JonathanLennox** [comment]
Is the change to how `muteAllNonModeratorParticipants` works related, or should that be a separate PR?

**Comment by bgrozev** [comment]
Its relatted in that it touches the same code. Do you want a separate PR for it?

**Comment by JonathanLennox** [comment]
> Its relatted in that it touches the same code. Do you want a separate PR for it?

Not necessary, but the commit message should mention it.

**Review by JonathanLennox — APPROVED** [review]

**Comment by bgrozev** [comment]
> Not necessary, but the commit message should mention it.

It does below the fold, but GH doesn't show the full message unless you click the commit.

**Pull request merged**
