### PR TITLE
feat: Adds a ping to the healthcheck.

### PR DESCRIPTION
**Pull request by damencho**
Adds a ping that will get its response in the single thread that handles the sync stanza listeners and will detect if something is blocking it.

### CODE REVIEW

**Comment by paweldomas** [comment]
Usually the requests for conference being created (the first one seen for given conference name) takes longer than usually and I don't remember if are blocking. I'd recommend testing this throughly as it's a risky one.

Isn't it enough to check how long the conference creation took? Or what problem does this PR solve?

**Comment by paweldomas** [comment]
Also if it's the `focusManager.getConference(roomName)` call that is stuck then ping will not detect it

**Comment by damencho** [comment]
It detects whether the single-threaded executor in smack is blocked.

**Comment by damencho** [comment]
> Usually the requests for conference being created (the first one seen for given conference name) takes longer than usually and I don't remember if are blocking. I'd recommend testing this throughly as it's a risky one.

Yeah, it waits for the creation of the room (response to the presence) and is executed in the smack reader thread but that code had not changes, I just add an extra packet for the check and its response ... 
I don't understand what worries you here, is that we would not receive the ping for 500ms on localhost?
I can adjust the time, for example in jvb the reply timeout is 5 seconds, where in jicofo and jigasi it is 15 seconds.

**Comment by paweldomas** [comment]
> I don't understand what worries you here, is that we would not receive the ping for 500ms on localhost?

So the first thing that may not work here is the case where the health check will block itself (the conference request). This will not be detected by ping, because it's sent after and if this call returns.

Another thing is that 500ms is too short and even if the IQ processor is not blocked, but it's just busy creating the conference this limit will likely be exceeded.

Also there's the assumption that everyone deploys jicofo and prosody on the same host.

> I can adjust the time, for example in jvb the reply timeout is 5 seconds, where in jicofo and jigasi it is 15 seconds.

Right, so 5 seconds and 15 that is for regular IQs. What problem will adjusting the timeout solve here?

**Comment by damencho** [comment]
> Another thing is that 500ms is too short and even if the IQ processor is not blocked, but it's just busy creating the conference this limit will likely be exceeded.

This is done after the conference is created, I don't see the connection here...

> Right, so 5 seconds and 15 that is for regular IQs. What problem will adjusting the timeout solve here?

That the wait will not be 500ms.

**Comment by paweldomas** [comment]
>> Another thing is that 500ms is too short and even if the IQ processor is not blocked, but it's just busy creating the conference this limit will likely be exceeded.

> This is done after the conference is created, I don't see the connection here...

But a user can be creating a conference at the time when healtcheck tries the ping.

**Comment by damencho** [comment]
> But a user can be creating a conference at the time when healtcheck tries the ping.

And? ... there is nothing that is blocking the creation of a conference. Creating a conference in healthcheck or from a user is just new muc created and joined, which is a presence we send and we receive its reply. The reply comes from a stanza collector which is executed in smacks reader thread. 

The ping is sent directly using the connection and we create a stanza listener which is added to the sync listeners and we check whether it is received, the wait is in a separate thread and the reply comes from a single-threaded executor, which is used for example for delivering presence updates on member joined.
There are no touchpoints between the ping and the creation of the room other than both received packets which are read from the reader thread in smack, but here we are blocking another thread. 

Where do you think ping can block the creation of a conference for a user?

**Comment by paweldomas** [comment]
> Where do you think ping can block the creation of a conference for a user?

I'm not saying that ping can block conference creation, but that ping can be blocked by a normal conference creation request that is just taking more time. That is probably more of a problem with the timeout set to 500ms, otherwise I guess it's fine.

**Comment by damencho** [comment]
Changed it to the reply timeout, whatever is configured.

**Comment by paweldomas** [comment]
> Changed it to the reply timeout, whatever is configured.

But do you agree that what I'm writing about could be the case? Because I'm no longer sure I understand everything here.

**Comment by damencho** [comment]
Well, I saw that the iqRequest handlers are sync mode and those are coming from another single thread and we block it till the  room is created, the presence response is delivered. We do not block the smacks reader thread. So I don't think creating of the rooms block in anyway ping. But I agree about the assumption the jicofo and prosody are on the same machine, and waiting for the timeout is also fine, it is longer ... hum ... it will miss shorter blockages ... for example because of dialout we saw it was blocked for 10 seconds, and if the replyTimeout is 15 seconds healthcheck will succeed and will miss that ...  @bgrozev WDYT, as you were also looking at this?

**Comment by bgrozev** [comment]
Ahh, now that ConferenceIq is handled in the smack sync thread, we end up executing JitsiMeetConferenceImpl#start there (which blocks waiting to join the MUC). This can explain the delays Pawel is seeing (I think we saw some indirect evidence of these too in prod). We'll have to solve this somehow, probably by offloading the smack sync thread again.

I think doing a ping in the health checker is fine -- if something blocks it for 5 seconds that's clearly a problem whatever the cause.

**Comment by paweldomas** [comment]
> Well, I saw that the iqRequest handlers are sync mode and those are coming from another single thread and we block it till the room is created, the presence response is delivered. We do not block the smacks reader thread.

If conference/muc queues are separate from ping then I don't know what the ping is supposed to detect.

**Comment by damencho** [comment]
> Ahh, now that ConferenceIq is handled in the smack sync thread, we end up executing JitsiMeetConferenceImpl#start there (which blocks waiting to join the MUC).

Ah, I see where the confusion comes from (confusing me), so I was talking about presence listeners which are smack sync listeners https://github.com/jitsi/Smack/blob/4fa73bde03b27b9166809ca6c2e5ebafe7d844b7/smack-extensions/src/main/java/org/jivesoftware/smackx/muc/MultiUserChat.java#L315 which are executed in the same thread as the ConferenceIqs, we want to detect whether something is blocking that thread.
So if that thread is blocked the sync listener we add with this change will also be blocked.

@bgrozev So the point here is that this PR is supposed to detect those 10 sec locks we saw ... but waiting 15 second for the ping will actually miss them. I will lower the wait time to 5 secs, wdyt?

**Comment by bgrozev** [comment]
This PR makes sense to me. @paweldomas what do you think?

I'll be working separately on handing ConferenceIq in a different thread.

**Review by bgrozev — APPROVED** [review]

**Pull request merged**
