### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by neilzone**
Added a note to Secure Domain configuration on how to create a Prosody user.

### CODE REVIEW

**Comment by saghul** [comment]
Looks good, thanks @neilzone! Have you signed the CLA mentioned above? Cheers!

**Comment by neilzone** [comment]
No - when I try to do so gives an error:
_Unable to submit form data, Error: An error has occurred._

(And that's leaving aside the point about requiring a CLA for such a small patch!)

**Comment by saghul** [comment]
@neilzone I'll pass the message along.

**Comment by kpfleming** [comment]
I'm just now following the Secure Domain setup instructions: does this command *replace* the `register` command? It seems to duplicate the information.

**Comment by saghul** [comment]
@kpfleming Oops, you're right.

**Pull request closed without merging**
