### PR TITLE
Shared document using room name config

### PR DESCRIPTION
**Pull request by yanas**

### CODE REVIEW

**Comment by yanas** [comment]
I've made sure that it won't return null and the null case is taken care of in the JitsiMeetConfig file.

**Comment by paweldomas** [comment]
How do we want the room name to look like ? Currently the value passed there is full MUC address, do we want to have there just the name ? It is all lower case.

**Comment by yanas** [comment]
It should be just the room name all lower case.

**Comment by paweldomas** [comment]
jenkins test this please

**Pull request merged**
