### PR TITLE
Added mute video moderation feature

### PR DESCRIPTION
**Pull request by skolmer**
This change adds the ability for a moderator to deactivate the camera of other participants. The implementation uses the same approach that was implemented to mute audio of other participants.

This feature consists of multiple PRs:
- https://github.com/jitsi/jitsi-media-transform/pull/329
- https://github.com/jitsi/jitsi-videobridge/pull/1570
- https://github.com/jitsi/jitsi-xmpp-extensions/pull/37
- https://github.com/jitsi/jicofo/pull/695
- https://github.com/jitsi/lib-jitsi-meet/pull/1496
- https://github.com/jitsi/jitsi-meet/pull/8630

### CODE REVIEW

**Comment by skolmer** [comment]
The build currently fails because it depends on jitsi/jitsi-xmpp-extensions#36

**Comment by damencho** [comment]
Yeah to run tests on all PRs together, the branch name should be the same ... I don't know how hard is for you to change that ... but we can try proceeding with the PRs, it is just this week is a little crazy for the team ...

**Comment by damencho** [comment]
The github actions compile fails in this situation this is know to happen, so ignore that.

**Comment by skolmer** [comment]
> 
> 
> Yeah to run tests on all PRs together, the branch name should be the same ... I don't know how hard is for you to change that ... but we can try proceeding with the PRs, it is just this week is a little crazy for the team ...

No problem I will close the jitsi-xmpp-extensions PR and create a new one that is based on the right branch name.

**Comment by damencho** [comment]
Jenkins, test this please.

**Comment by damencho** [comment]
Hey, @skolmer thanks for your contribution. 
You can update here the pom file with jitsi-xmpp-extensions - 1.0-19-g7f14fef. Thanks.

**Review by damencho — DISMISSED** [review]

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Jenkins, test this please.

**Pull request merged**
