### PR TITLE
Adds class loader for bundles

### PR DESCRIPTION
**Pull request by sidorovis**
related to https://github.com/jitsi/jicoco/pull/31

### CODE REVIEW

**Comment by sidorovis** [comment]
@damencho jicoco version updated according to result artifact 1.1-20180327.183532-3

**Comment by damencho** [comment]
Hey @sidorovis, I know we already merged half of the work :) but one question. This method getPlatformClassLoader is it possible to be in a common place? Like utility or something, currently we have it in jitsi-android-osgi, jicoco, jvb and jicofo?

**Comment by bgrozev** [comment]
@sidorovis we had to fix version of jicoco in jicofo/pom.xml because the tests don't pass with -SNAPSHOT. You might need to resolve conflicts.

**Comment by sidorovis** [comment]
@damencho there is a small issue with this getPlatformClassLoader method. It's used as part of project only at jicoco. 
For jicofo, jitsi-videobridge and jitsi-android-osgi it used only for tests. 
So from my point of view is next: the best practice is to make "jitsi-tests" project for such dependencies. This provide possibility to mark at pom.xml that only tests are dependent.

**Comment by sidorovis** [comment]
@damencho merged

**Comment by damencho** [comment]
@sidorovis Strange, I still see "This branch cannot be rebased due to conflicts"

**Comment by sidorovis** [comment]
"This branch has no conflicts with the base branch" for my side. 
And merge pull request #217 from bgrozev/jvb-full-jid as a last merged commit.

**Comment by damencho** [comment]
That is so strange: 
screen shot 2018-04-02 at 10 58 46
Don't you see the same?

**Comment by bgrozev** [comment]
An automatic rebase is not available, a normal merge and squash are available.

**Comment by sidorovis** [comment]
screen shot 2018-04-02 at 7 05 53 pm

**Comment by damencho** [comment]
Silly me, sorry for the noise.

**Pull request merged**
