### PR TITLE
Adding instructions for building the package from source

### PR DESCRIPTION
**Pull request by dmikushin**
It took me some time to get through https://github.com/jitsi/jicofo/issues/30 and figure out what steps are needed for successful command-line compilation. This PR proposes to add at least minimal directions into the README to simplify the developer experience, especially for those who are not native Java-speakers.

### CODE REVIEW

**Comment by damencho** [comment]
For having just the jicofo.jar, why not just use `mvn install` the default command for every maven project ... ?

**Comment by damencho** [comment]
Ant is just used for creating debian packages, the rest is in maven.

**Comment by bgrozev** [comment]
I would also suggest using `mvn install -Dassembly.skipAssembly=false` to generate the zipped packages (which can be used manually as a replacement for `/usr/share/jicofo` in a debian installation).

**Comment by dmikushin** [comment]
Thank you for your feedback! I've used ant specifically in order to make a
local build for development purposes. That is, jicofo.jar is generated in
the build folder and can be manually copied into existing Jitsi
installation, without any packaging. Do you mean that mvn install can also
be used for this?

ср, 25 сент. 2019 г. в 13:16, bgrozev <notifications@github.com>:

**Comment by bgrozev** [comment]
Yes, we recommend always using maven instead of ant. Just running `mvn install` should be enough to produce a new `jicofo.jar`. However, replacing `jicofo.jar` alone may not be sufficient because some of the dependencies may have changed (especially if you are working on some of the underlying libraries instead).

My procedure for manually building a custom version and deploying it to an existing remote installation is the following:
```
local$ mvn install -Dassembly.skipAssembly=false
local$ scp target/jicofo-linux-x64-1.1-SNAPSHOT.zip $remote

remote$ unzip jicofo-linux-x64-1.1-SNAPSHOT.zip
remote$ sudo mv /usr/share/jicofo /usr/share/jicofo-orig
remote$ sudo ln -s $HOME/jicofo-linux-x64-1.1-SNAPSHOT /usr/share/jicofo
remote$ sudo service jicofo restart
```

**Comment by bgrozev** [comment]
Thank you for your contribution and apologies for the lack of response. I cleaned up the readme and I think I picked up your suggestions.

**Pull request closed without merging**
