### PR TITLE
Adds RTX by default to offers

### PR DESCRIPTION
**Pull request by bgrozev**
Cleans up JingleOfferFactory. Removes RED, ULPFEC and some unused audio formats from the offer, and adds RTX. RTX is optionally disabled on a per-conference basis by setting disableRtx=true in the conference creation request (or adding #config.disableRtx=true to the URL in Jitsi-Meet).

Note: this needs jitsi-videobridge#209 (not directly, but stuff will be broken without it).

### CODE REVIEW

**Comment by paweldomas** [comment]
@bgrozev not sure if this PR's intention was to add RTX to offer by default, from the code it looks like it is added only when peer supports it, am I missing something ? I'm asking because PR title says something different and if it is meant to be always included by default then it should also end up here https://github.com/jitsi/jicofo/blob/master/src/main/java/org/jitsi/jicofo/discovery/DiscoveryUtil.java#L193

**Comment by bgrozev** [comment]
Good catch, Pawel, I hadn't thought of this.

There's two parts.  The per-conference configuration: if it is false, no one in the conference will be offered rtx. This is the part controlled through disableRtx, and it defaults to enabled. Then there's the per-participant part which will not include rtx in the offer unless it has advertised support. I think that keeping the default here to 'false' is safer, since adding rtx for a participant that doesn't support it will break retransmissions for it.

**Comment by paweldomas** [comment]
Yes, it's better to keep it this way

**Comment by paweldomas** [comment]
Hey @gpolitis why have you merged the PR when the tests have failed :P ? There is complication error on "test" part where method signatures have changed

**Comment by paweldomas** [comment]
https://github.com/jitsi/jicofo/commit/178d0a3edb7924f37ed0d54ea7ce920a503e034a

**Comment by gpolitis** [comment]
I'm sorry, I apologize for this @paweldomas, I merged this too quickly.

**Pull request merged**
