### PR TITLE
ref(Health):  auto enable on first REST request

### PR DESCRIPTION
**Pull request by paweldomas**
...if org.jitsi.jicofo.health.ENABLE_HEALTH_CHECKS
is not set. This also preserves the previous behavior
from before the most recent health checks refactor.

Also fixes an issue where the health checks would return
500 error instead of always success if not enabled what
was written in the docs.

### CODE REVIEW

**Comment by bbaldino** [comment]
This seems kinda weird...if we're just going to automatically turn them on, what's the point of the configuration value at all?

**Comment by paweldomas** [comment]
> This seems kinda weird...if we're just going to automatically turn them on, what's the point of the configuration value at all?

To be able to disable.

**Comment by paweldomas** [comment]
> This seems kinda weird...if we're just going to automatically turn them on, what's the point of the configuration value at all?

We use health checks by default, but the community complains about those checks enabled by default. In order to have less config properties I want to do it this way.

**Comment by bbaldino** [comment]
> > This seems kinda weird...if we're just going to automatically turn them on, what's the point of the configuration value at all?
> 
> To be able to disable.

But they aren't really disabled, because a request turns them on?

**Comment by paweldomas** [comment]
@bbaldino 
It may seem weird, but I want to have as little config as possible.

**Comment by bbaldino** [comment]
Ok, I guess I don't have all the context, but it seems like the health checks should just either be enabled or not.  If community doesn't want them, then they can just disable them in the config? I don't follow why we need the config value, but also this 'auto enable' thing if a request is made.

**Comment by paweldomas** [comment]
> Ok, I guess I don't have all the context, but it seems like the health checks should just either be enabled or not. If community doesn't want them, then they can just disable them in the config? I don't follow why we need the config value, but also this 'auto enable' thing if a request is made.

What I said above, to have less config properties to set.

**Comment by paweldomas** [comment]
> then they can just disable them in the config?
Well they can, but it was a recent change in the behavior where they didn't have to do that.

**Comment by bbaldino** [comment]
> > Ok, I guess I don't have all the context, but it seems like the health checks should just either be enabled or not. If community doesn't want them, then they can just disable them in the config? I don't follow why we need the config value, but also this 'auto enable' thing if a request is made.
> 
> What I said above, to have less config properties to set.

I'm not sure I understand why we want to avoid this, as config properties aren't a big deal (it'd be on by default and disable-able by the community) and this is exactly the sort of thing config values are useful for?

Anyway, it's done now, but this seems like an appropriate use of config to me.  Changing this value on upgrades doesn't seem like the worst "breakage" to me, either.  But, again, it's done so I can drop it.

**Comment by paweldomas** [comment]
> I'm not sure I understand why we want to avoid this, as config properties aren't a big deal (it'd be on by default and disable-able by the community) and this is exactly the sort of thing config values are useful for?

Didn't you say or agree with me recently that our configs are too complex :P ? It's just part of trying to reduce the amount of configs required. Try to have the default code behavior match the most use cases.

**Comment by paweldomas** [comment]
Will it not be good if we get less questions on the community forum that people's configs are suddenly broken?

**Pull request merged**
