### PR TITLE
Adding focus listeners to a set

### PR DESCRIPTION
**Pull request by rdsmallwood928**
Protecting set on listener set

Removing unneccesary comment

Changing set to list as that is what is specified in the
code...

Some test code to make sure the FocusListeners are getting
destroyed as expected...

Removing debug code

Some debugging code for conference timeouts...

Get room is not a method for conference :/

Debugging conference map

Changing listener to listeners

Reverting 100-Continue stuff

### CODE REVIEW

**Comment by rdsmallwood928** [comment]
Currently conference deletions are not being received by our reservation system.  This change would allow for multiple FocusListeners so that the listeners don't overwrite each other. I believe this would also fix this issue https://github.com/jitsi/jicofo/issues/39

**Comment by FearTheBadger** [comment]
We have signed a corporate agreement, can you add me to the list with @rdsmallwood928.
@PetroccoCo, @CPWeaver or @dwilson6 can verify.

**Comment by PetroccoCo** [comment]
I can confirm @Fearthebadger is covered under our corporate agreement.

**Comment by dihedral** [comment]
what happend? is this no longer of interes?

**Comment by FearTheBadger** [comment]
The company who was working on this we bought, and the product was shelved. So those who worked on this have no vested interest.

Not to say that this shouldn't still be merged after fixing the conflict, but we have lost our vestment.

**Comment by bgrozev** [comment]
Thanks for your contribution. I don't think this valid anymore (we already have a list)

**Pull request closed without merging**
