### PR TITLE
feat: Passes room bare jid to conference IQ.

### PR DESCRIPTION
**Pull request by damencho**
Depends on https://github.com/jitsi/jitsi-xmpp-extensions/pull/31

### CODE REVIEW

**Comment by ibauersachs** [comment]
Why is this necessary? The room name is (or used to be...) part of the JID and cannot (could not) be a simple string.

**Comment by damencho** [comment]
This change is needed because of the multi tenant option of jitsi-meet. And this is the name for the conference ... it's not a jid, and is used only for logging and stats (callstats and siteId).
The conferences can be without tenant `roomName` or with a tenant `someCompany/roomName`. Converted to jid, this would be `roomName@conference.someCompany.jitsiexample.com`. And internally in prosody this is converted and handled as jid `[someCompany]roomName@conference.jitsiexample.com`.
This change is to be able to send that siteId to callstats.
For example before this change if you have a meeting https://meet.jit.si/ingo/roomName and another one https://meet.jit.si/damencho/roomName and if you filter logs by roomName you will get logs for both conferences with no mention of the tenant, which will be improved by this change.

**Comment by ibauersachs** [comment]
It's been a while, but this sounds really weird... wouldn't nginx or whatever is actually creating the rooms in Prosody do the translation/mapping from orgName/confname into confname@orgname.meet.example?

And the change on line 731 might not be what you want if I understand your explanation correctly.

**Comment by damencho** [comment]
> It's been a while, but this sounds really weird... wouldn't nginx or whatever is actually creating the rooms in Prosody do the translation/mapping from orgName/confname into [confname@orgname.meet.example](mailto:confname@orgname.meet.example)?



> It's been a while, but this sounds really weird... wouldn't nginx or whatever is actually creating the rooms in Prosody do the translation/mapping from orgName/confname into [confname@orgname.meet.example](mailto:confname@orgname.meet.example)?

Well yeah its a dynamic config.js based on the URL that is served to the client then a prosody module do the conversion to the existing domain part of the jid.



> And the change on line 731 might not be what you want if I understand your explanation correctly.
Ohm yes, I got confused, yeah we are sending the whole jid ... and leave it to be parsed only in one place https://github.com/jitsi/jitsi-stats/pull/10/files#diff-76beb6d96152820b241eb7dd1f5eb65bR116 which is common for jigasi and jvb ...

**Comment by ibauersachs** [comment]
The changes in jitsi-stats make a lot more sense to me than what is done here. As for the string-fiddling with the domain name there, you could consider using `Name` from dnsjava.

**Comment by damencho** [comment]
Well, this will bring dnsjava to a lot of places as we need to make it a dependency of jitsi-xmpp-extensions where this is just a name ... I will update javadoc of jitsi-xmpp-extensions explaining what is the name and how it is used.

**Comment by damencho** [comment]
And it already says "World readable name for the conference." ...

**Comment by bgrozev** [comment]
> The changes in jitsi-stats make a lot more sense to me than what is done here.

The other option we had was to do the interpretation of "domain", "tenant" and "conference name" in jicofo, then pass it as 3 parameters to the bridge, only for it to re-construct a single string from them again. This also requires the same parsing code in jigasi.

**Review by bgrozev — APPROVED** [review]

**Review by bgrozev — APPROVED** [review]

**Pull request merged**
